server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios
    username: root
    password: elieta103
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: USUARIO-SERVICE

  config:
    import: optional:configserver:http://localhost:8085
  #profiles:
    #active: dev

