server:
  port: 8086

spring:
  application:
    name: AUTH-SERVICE
  config:
    import: configserver:http://localhost:8085
  profiles:
    active: dev

jwt:
  secret: secret

admin-paths:
  paths:
    -
      uri: "/usuarios"
      method: "POST"
